### ISSUE TITLE
Semver matching seems to always cause "invalid version"

### ISSUE THREAD

**Issue by evantahler** [defunctzombie/docserv#4]
For example, if I have `"async":"0.1.x",` in my `package.json`

**Comment by defunctzombie** [comment]
Can you elaborate on this a bit more?

**Comment by evantahler** [comment]
Sure! 

Here's the docserv for https://github.com/evantahler/actionHero

![actionHero](https://f.cloud.github.com/assets/303226/37688/fb941246-5493-11e2-9209-4a671a50bf0e.jpg)

ActionHero's `package.json` https://github.com/evantahler/actionHero/blob/master/package.json

Just about every dependency is listed as `invalid version`, and I _think_ it is because the versions of each package are not explicitly defined, rather they use fuzzy smever matching (1.2.x, etc).   

If that's the case, it's not that versions are 'invalid', but just defined loosely.  If module maintainers like yourself keep to the rule that updates to a version which only change the third decimal are non-breaking, than this type of dependency graph should be OK in most cases.

**Comment by evantahler** [comment]
Oh, I put docserv in as a devDependency, so you can clone the project and try it out for yourself

**Comment by evantahler** [comment]
Thanks!
