### ISSUE TITLE
export the express application

### ISSUE THREAD

**Issue by juliangruber** [defunctzombie/docserv#9]
...and move `app.listen` to the bin script.

This way I can mount docserv at `/doc` inside my project, for super awesomeness

**Comment by juliangruber** [comment]
If this were fully mountable that'd be awesome.

What I've done for an application is I changed all the paths manually and then serve the documentation at `/doc`. The mounted path is readable at `app.path`

**Comment by defunctzombie** [comment]
published with v0.1.0 and documented on the readme
